[package]
name = "my-app"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.1"
egui_extras = "0.31.1"
image = "0.25.6"
rfd = "0.15.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
